{"trial_id": "0002", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"units": 384, "learning_rate": 0.001, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {"loss": {"direction": "min", "observations": [{"value": [0.370826780796051], "step": 1}]}, "accuracy": {"direction": "max", "observations": [{"value": [0.8644375205039978], "step": 1}]}, "val_loss": {"direction": "min", "observations": [{"value": [0.38146668672561646], "step": 1}]}, "val_accuracy": {"direction": "max", "observations": [{"value": [0.8607500195503235], "step": 1}]}}}, "score": 0.8607500195503235, "best_step": 1, "status": "COMPLETED", "message": "Traceback (most recent call last):\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"E:\\LocalRepository\\Anaconda3_envs\\deeplearning\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\nTypeError: Model.fit() got an unexpected keyword argument 'label_trainepochs'\n"}